// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASqAaz7UoN9ZaW9oGo3sax1WN0k0ZSxCk',
    appId: '1:1096685931641:web:b1f62f03af3ec9670b58a8',
    messagingSenderId: '1096685931641',
    projectId: 'part30-firebase',
    authDomain: 'part30-firebase.firebaseapp.com',
    storageBucket: 'part30-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBu_rsTZQyvQHgsa2CLAe9NjRxAx0qb8',
    appId: '1:1096685931641:android:db490a7f3523bbf70b58a8',
    messagingSenderId: '1096685931641',
    projectId: 'part30-firebase',
    storageBucket: 'part30-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWIkgAmio8srY2ziMo16yvndnyUsybzoU',
    appId: '1:1096685931641:ios:3fa7fc09db2c14710b58a8',
    messagingSenderId: '1096685931641',
    projectId: 'part30-firebase',
    storageBucket: 'part30-firebase.firebasestorage.app',
    iosBundleId: 'com.nazifeatmaca.part30Firebase',
  );
}
